server:
  port: 8779
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_development
    username: oauth2
    password: oauth2
security:
  oauth2:
    client:
      access-token-uri: http://localhost:8778/oauth/token
      user-authorization-uri: http://localhost:8778/oauth/authorize
      client-id: 70d7c0424190ec81726664d1dd93cfe5
