server:
  port: 8778
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/oauth2_development
    username: oauth2
    password: oauth2
security:
  oauth2:
    resource:
      user-info-uri: http://localhost:8778/user
      prefer-token-info: false