server:
  port: 8777
spring:
  cloud:
    stream:
      bindings:
        input:
          destination: cloud.task
          group: queue
        output:
          destination: cloud.task
          contentType: application/json
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/task_development
    username: task
    password: task
    